### ISSUE TITLE
Migrate to now and next.js

### ISSUE THREAD

**Issue by floatdrop** [getbem/getbem.github.io#125]
I think it would be cool to migrate from gh-pages to [now](https://zeit.co/now) and [next.js](https://github.com/zeit/next.js) (it's super cool!).

//@iamstarkov what do you think?

**Comment by iamstarkov** [comment]
as far as im aware now supports custom domains only in paid plan

**Comment by floatdrop** [comment]
It’s time to rework site a little. I thing Astro+Solid.jd+Tailwind would be good as starting ground (although I would prefer deno with fresh, but fresh does not supports ssg).
