### ISSUE TITLE
Grammatical Error in naming.js

### ISSUE THREAD

**Issue by ashnehete** [getbem/getbem.github.io#142]
https://github.com/getbem/getbem.com/blob/master/src/views/naming.js#L49

"Parts of a block and have no standalone meaning. Any element is semantically tied to its block."

What does this sentence mean?

**Comment by code-warrior** [comment]
It’s possible that it might read better as follows:

“Children of a block element have no standalone meaning — every child of a block is semantically tied to its block.”
