### ISSUE TITLE
FAQ section links redirect to pages without content loaded

### ISSUE THREAD

**Issue by borowyalan** [getbem/getbem.github.io#182]
When clicking one of two links on the FAQ section of the web [showed on image], 

![obraz](https://user-images.githubusercontent.com/38703820/46247013-a95b1780-c405-11e8-86d1-c068afc2a66c.png)

they redirect you to the site looking like this. URL is somehow valid because it fixes itself after a reload of the page.

![obraz](https://user-images.githubusercontent.com/38703820/46247028-dc051000-c405-11e8-89cf-84929061fdce.png)

Tried on the newest firefox and chrome [29.09.2018].

**Comment by robaxelsen** [comment]
Same issue reproducible for me, using Chrome 75.
