### ISSUE TITLE
Support for the HTTPS scheme should be added and enforced

### ISSUE THREAD

**Issue by oboukli** [getbem/getbem.github.io#190]
Do we need HTTPS? Yes. See https://doesmysiteneedhttps.com/

Once enabled, I'm happy to create a pull request to update the links on the website/README.

BTW, [GitHub Pages with custom domains do support HTTPS](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/).

**Comment by kachkaev** [comment]
The website no longer works in [Firefox with HTTPS-Only Mode on](https://blog.mozilla.org/security/2020/11/17/firefox-83-introduces-https-only-mode/).

![Screenshot 2020-12-04 at 18 05 51](https://user-images.githubusercontent.com/608862/101198439-60452480-365b-11eb-980a-a1a015c91b67.png)

🙏
