### ISSUE TITLE
since the domain name is getbem.com, what can we get/download from this?

### ISSUE THREAD

**Issue by imakin** [getbem/getbem.github.io#199]
The website is named getbem.com which put in mind that there is something that we can get from this website. Would be nice to have some stuff to download: tools, chrome/firefox plugin for BEM score, or reusable css?

**Comment by alevfalse** [comment]
Knowledge.

**Comment by pbb72** [comment]
To "get it" can also mean to understand it. Got it? 😉 But I agree, the domain name makes you expect you can download something here.
