### ISSUE TITLE
SSL Not Trusted

### ISSUE THREAD

**Issue by jsphpndr** [getbem/getbem.github.io#201]
https://getbem.com is returning a warning:

> 
> Your connection is not private
> Attackers might be trying to steal your information from getbem.com (for example, passwords, messages, or credit cards). Learn more

You may want to check that out.

**Comment by eddie-craftsmanshipcounts** [comment]
This is happening again. I was there just the other day, and it worked fine, but this morning I'm getting the cert warning again in Chrome on Mac.

**Comment by eddie-craftsmanshipcounts** [comment]
![image](https://user-images.githubusercontent.com/6170865/125307607-d1d20900-e2f5-11eb-819d-4685990a0bf7.png)

**Comment by domainfun** [comment]
_Slightly separate but related:_  It appears that there is no automatic redirection from ```http://getbem.com/``` to ```https://getbem.com/```.  This is something which is ideally done with a "301 Moved Permanently" HTTP status code.

This would also fix what's been reported in https://github.com/getbem/getbem.github.io/issues/190.
