### ISSUE TITLE
FAQ: How come you are using global, element level resets on getbem.com when you recommend against it?

### ISSUE THREAD

**Issue by d-Pixie** [getbem/getbem.github.io#209]
Hi.

While trying to square our real world lives with BEM best practices we came to the question about CSS reset. I do like your approach from the FAQ, but since we have done some CSS diving on your site - to see how you do things - I also know that you use Milligram as the CSS base for that site and it does CSS reset for you ...

How does that play in to the overall BEM philosophy? As an example, your `.panel h2` doesn't reset it's `line-height`, but relies on the global `h2` `line-height` reset from Milligram, and will break if you change the global `h2` `line-height`.

Is this an oversight, pragmatism or am I just trying too hard to stick to the rules here?

**Comment by floatdrop** [comment]
Milligram will be removed in next site iteration. I don’t think css resets are forbidden by BEM though.
