### ISSUE TITLE
BEM extension for React

### ISSUE THREAD

**Issue by coreprocess** [getbem/getbem.github.io#304]
At Revin, we're big fans of the BEM methodology and have implemented it across all our code bases. To help increase the adoption of BEM internally and beyond, we've just released a small React extension that we're excited to share with you.

https://www.npmjs.com/package/react-with-bem

We welcome your feedback and bug reports, and if you have ideas for improvement, feel free to open a pull request.

We apologize for posting here, but we believe it is a valuable contribution to the BEM ecosystem, and we hope that it can be helpful to others who are interested in utilizing the BEM methodology.

**Comment by floatdrop** [comment]
This is very close to spam posting issues. Please use Reddit or Hacker news to promote libraries.

**Comment by coreprocess** [comment]
@floatdrop We apologize if our post inadvertently gave off a negative impression. Our aim was simply to share our work as a valuable addition to the BEM ecosystem. This library has been a game changer for us, allowing us to utilize BEM without incurring extra overhead.
