### ISSUE TITLE
Add #4 reason to Why the modifier CSS classes are not represented as a combined selector?

### ISSUE THREAD

**Issue by ihorzenich** [getbem/getbem.github.io#71]
In FAQ section „Why the modifier CSS classes are not represented as a combined selector?“ please add:

> You get problem with mixing 2 blocks with shorted modifiers - rules for block modifiers 
> 
> ```
> .block1.-mod {}
> .block2.-mod {}
> ```
> 
> will have the same specificity as rules for block mix 
> 
> ```
> .block1.block2 {}
> ```
> 
> and can unexpectedly override them.

**Comment by floatdrop** [comment]
//cc @varya

**Comment by floatdrop** [comment]
@ihorzenich 

I'm not quite sure, where exactly you want to make addition. Seems like your version can duplicate part of [this paragraph](https://github.com/getbem/getbem.com/blob/master/src/views/faq.js#L37):

> Another point is CSS specificity. The combined selectors are more specific (means more important) than single class selectors. This means that you might have trouble when redefining them with parent block code.

Can you send a PR into [faq.js](https://github.com/getbem/getbem.com/blob/master/src/views/faq.js) directly?
