### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by moonsin** [getbem/getbem.github.io#73]
I pushed it to my github.I can commit it .

**Comment by floatdrop** [comment]
@moonsin sweet! I think we can workout subdomain (like `cn.getbem.com`) from complete translation of site.

//cc @varya @iamstarkov

**Comment by moonsin** [comment]
haha.this is good idea .then i can help you though my English is not so good.

**Comment by iamstarkov** [comment]
chinese subdomain sounds like a good idea

**Comment by moonsin** [comment]
i will have a long holiday after next week.then i can help u.i can learn more before that.

**Comment by floatdrop** [comment]
@moonsin we got subdomains running - http://cn.getbem.com/faq/

But for now there is no workflow for translation, so I published it by hands. If someone have ideas – how to automate it, please share :star:

**Comment by moonsin** [comment]
@floatdrop : ) i am very glad i can help you.i think BEM is a good  methodology.so,it's my honor to help Chinese people  read this website.I think i can just translate hole work by hand since the information here is not too much,but  it may be a long-term work because i am working in a company these days.btw,one point concerned me is that my English is not too good,so maybe i made some mistakes,so,i will review and check it in the future.

**Comment by tolerious** [comment]
maybe we can write it on gitbook for different language version.

**Comment by moonsin** [comment]
哈哈，我把FAQ大致翻译了一下，剩下的你可以把别的也翻译好，然后直接开一个国语的版本 @tolerious

**Comment by floatdrop** [comment]
To be resolved in #287
