### ISSUE TITLE
No FAQ anchor links on landing page work

### ISSUE THREAD

**Issue by fatso83** [getbem/getbem.github.io#87]
To reproduce:
1. Go the http://getbem.com
2. Scroll down to the FAQ section
3. Press one of the two first links. 

You are then presented with [an empty page](http://getbem.com/faq/#custom-tags-for-blocks)

**Comment by iamstarkov** [comment]
strange, cannot reproduce. can you provide (os & browser) version? while i cannot reproduce, can you also show some kind of gif or video?

**Comment by fatso83** [comment]
I'll get to it tomorrow, hopefully.

**Comment by floatdrop** [comment]
@fatso83 thanks! [This code](https://github.com/getbem/getbem.com/blob/master/src/main.js#L13-L26) is responsible for navigation and not working properly with anchor hashes.

**Comment by fatso83** [comment]
[Quicktime video showing the bug in Safari](https://www.dropbox.com/s/ib6tb2ep28c10qn/getbem.bug.mov?dl=1)

I have also tried the same in Chrome. Happens exactly the same thing.

Safari 9.1
Chrome 49
OS X 10.11.4
