### ISSUE TITLE
Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by tuhlsolucoes** [getbem/getbem.github.io#90]
Hi guys!
I'm a brazilian designer and developer and i'm currently looking to contribute on some open source projects. I stumbled across getbem and found the content to be super valuable, so i'm willing to translate it to portuguese, would it be ok?

**Comment by floatdrop** [comment]
@freitaseduardo of course! We still not have working plan, how to maintain translations, but some work was done in #73. I'm sure we figure something out.

**Comment by freitaseduardo** [comment]
Alright! Can we get the subdomain `br.getbem.com`?
I'm keeping the translated version on a fork until it's ready to ship, ok?

I noticed we have broken links in the licenses located on footer.js, is this something you can fix, or should i just remove the links?

Thanks!

**Comment by floatdrop** [comment]
@freitaseduardo
> Alright! Can we get the subdomain br.getbem.com?

Sure.

> I'm keeping the translated version on a fork until it's ready to ship, ok?

Let's start with this. Can yo send PR to branch `br-lang` afterwards?

> I noticed we have broken links in the licenses located on footer.js, is this something you can fix, or should i just remove the links?

I forgot to add licenses :blush: - now it's fixed.

**Comment by freitaseduardo** [comment]
> Let's start with this. Can yo send PR to branch br-lang afterwards?

I may need some help with some git stuff, currently i forked the repo and made a new branch called `br-lang`. Let's say i'm ready to deploy, what do i do?

**Comment by floatdrop** [comment]
@freitaseduardo you should create PR into `br-lang` branch in this repo. Make sure you change subdomain to `br.getbem.com` here - https://github.com/getbem/getbem.com/blob/cn-lang/package.json#L37 and name of branch to `br-lang` here - https://github.com/getbem/getbem.com/blob/master/.travis.yml#L8

After PR is merged site should be available on `br.getbem.com`.

**Comment by freitaseduardo** [comment]
Perfect, thank you! 😁

**Comment by lucasbento** [comment]
@freitaseduardo any news on this? I'm also willing to help! (:

**Comment by freitaseduardo** [comment]
Hi @lucasbento 😃
I'm still on the mission, it's a bit slow but i'm making progress.
Maybe we can get in touch somewhere else to see how we can work together on this?
Thanks in advance 👊🏾

**Comment by lucasbento** [comment]
@freitaseduardo send me an email, it's available on my profile.

Hope we get started soon! :D

**Comment by lucasbento** [comment]
@floatdrop maybe we could organize it as [babel-handbook](https://github.com/thejameskyle/babel-handbook/blob/master/translations/). It appears to be a better approach than branches.

**Comment by floatdrop** [comment]
To be resolved in #287
